version: '3.9'

services:
  php:
    image: gazie-php:8.02
    hostname: gazie
    volumes:
      - ./gconfig.myconf.example.php:/var/www/html/config/config/gconfig.myconf.php
    ports:
      - "8088:80"
    depends_on:
      - db
    networks:
      - gazie_net

  db:
    image: mysql:9.1.0
    hostname: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: gazie
      MYSQL_DATABASE: gazie
      MYSQL_USER: gazie
      MYSQL_PASSWORD: gazie
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - gazie_net

volumes:
  db_data:

networks:
  gazie_net:
    driver: overlay
    external: false

